[
  {
    name: "DANCE",
    gender: "both",
    registrationLastDate: "23rd Jan",
    minSize: 6,
    maxSize: 12,
    category: "cultural",
    poster: "group dance.png",
    details: "#",
    ename: "dance",
    type: "group",
  },
  {
    name: "CLASSICAL DANCE",
    gender: "both",
    registrationLastDate: "23rd Jan",
    minSize: 1,
    maxSize: 1,
    category: "cultural",
    poster: "classical.png",
    details: "#",
    ename: "classical-dance",
    type: "solo",
  },
  {
    name: "SEMI CLASSICAL",
    gender: "both",
    registrationLastDate: "23rd Jan",
    minSize: 2,
    maxSize: 2,
    category: "cultural",
    poster: "semi classical.png",
    details: "#",
    ename: "semi-classical",
    type: "duo",
  },
  {
    name: "SONGS",
    gender: "both",
    registrationLastDate: "23rd Jan",
    minSize: 1,
    maxSize: 1,
    category: "cultural",
    poster: "",
    details: "#",
    ename: "songs",
    type: "solo",
  },
  {
    name: "RAMP SHOW",
    gender: "both",
    registrationLastDate: "23rd Jan",
    minSize: 1,
    maxSize: 1,
    category: "cultural",
    poster: "ramp walk.png",
    details: "#",
    ename: "ramp-show",
    type: "solo",
  },
  {
    name: "FLASH MOB",
    gender: "both",
    registrationLastDate: "23rd Jan",
    minSize: 1,
    maxSize: 100,
    category: "cultural",
    poster: "flash.png",
    details: "#",
    ename: "flash-mob",
    type: "group",
  },
];
