const nontechData = [
  {
    name: "LAN GAMING (BGMI)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 4,
    maxSize: 5,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "lan-gaming-bgmi",
  },
  {
    name: "LAN GAMING (FIFA)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "lan-gaming-fifa",
  },
  {
    name: "LAN GAMING (COD)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 4,
    maxSize: 5,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "lan-gaming-cod",
  },
  {
    name: "LAN GAMING (NFS)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "lan-gaming-nfs",
  },
  {
    name: "LAN GAMING (VALORENT)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 5,
    maxSize: 6,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "lan-gaming-valorent",
  },
  {
    name: "MOBILE GAMING (BGMI)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 4,
    maxSize: 5,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "mobile-gaming-bgmi",
  },
  {
    name: "MOBILE GAMING (COD)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 4,
    maxSize: 5,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "mobile-gaming-cod",
  },
  {
    name: "MOBILE GAMING (FREE FIRE)",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 4,
    maxSize: 5,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "mobile-gaming-free-fire",
  },
  {
    name: "GIETU SPELLING BEE",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "gietu spelling bee.png",
    details: "#",
    ename: "gietu-spelling-bee",
  },
  {
    name: "PRECISE WRITING",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "precise writing.png",
    details: "PRECISE WRITING2.0.pdf",
    ename: "precise-writing",
  },
  {
    name: "E-MAIL WRITING",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "e-mail writing.png",
    details: "EMAIL2.0.pdf",
    ename: "e-mail-writing",
  },
  {
    name: "ESSAY WRITING",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "essay writing.png",
    details: "ESSAY2.0.pdf",
    ename: "essay-writing",
  },
  {
    name: "TECHSPEAK TRIUMPH",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    details: "#",
    poster: "TECHSPEAK TRIUMPH.png",
    ename: "techspeak-triumph",
  },
  {
    name: "EXTEMPORE",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "Extempore.png",
    details: "EXTEMPORE 2.0.pdf",
    ename: "extempore",
  },
  {
    name: "GIETU GOT TALENT",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "gietu got talent.png",
    details: "GIETU GOT TALENT 2.0.pdf",
    ename: "gietu-got-talent",
  },
  {
    name: "JUST A MINUTE",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "JAM.png",
    details: "JUST A MINUTE FINAL 2.0.pdf",
    ename: "just-a-minute",
  },
  {
    name: "BIZ-WAR",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "WIZWAR.png",
    details: "BIZ-WAR FINAL 2.0.pdf",
    ename: "biz-war",
  },
  {
    name: "TREASURE HUNT",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "Treasure hunt.png",
    details: "TREASURE HUNT FINAL2.0.pdf",
    ename: "treasure-hunt",
  },
  {
    name: "TECH ROADIES",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "Tech Rodies.png",
    details: "TECH ROADIES  FINAL2.0.pdf",
    ename: "tech-roadies",
  },
  {
    name: "ART GALLERY",
    gender: "female",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "Art galery.png",
    details: "ART GALLERY FINAL2.0.pdf",
    ename: "art-gallery",
  },
  {
    name: "CARD MAKING",
    gender: "female",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "card making.png",
    details: "Card designING 2.0.pdf",
    ename: "card-making",
  },
  {
    name: "NAIL PAINTING",
    gender: "female",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "NAIL PAINTING  FINAL2.0.pdf",
    ename: "nail-painting",
  },
  {
    name: "MEHENDI",
    gender: "female",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "mehendi.png",
    details: "MEHENDI FINAL2.0.pdf",
    ename: "mehendi",
  },
  {
    name: "RANGOLI",
    gender: "female",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "rangoli.png",
    details: "RANGOLI FINAL2.0.pdf",
    ename: "rangoli",
  },
  {
    name: "SMART BRID",
    gender: "female",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "bridal makeup.png",
    details: "#",
    ename: "smart-brid",
  },
  {
    name: "LIVE PAINTING",
    gender: "both",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "live painting",
    details: "LIVE PAINTING FINAL2.0.pdf",
    ename: "live-painting",
  },
  {
    name: "MUSICAL CHAIR",
    gender: "female",
    registrationLastDate: "21th Jan",
    minSize: 1,
    maxSize: 1,
    category: "non-technical",
    fees: "Free",
    poster: "musical chair.png",
    details: "MusicAL chair FINAL2.0.pdf",
    ename: "musical-chair",
  },
  {
    name:"DIGITAL REEL",
    gender:"both",
    registrationLastDate:"21th Jan",
    minSize: 1,
    maxSize: 5,
    category: "non-technical",
    fees: "Free",
    poster: "",
    details: "#",
    ename: "digital-reel",
  }
];

module.exports = { nontechData };
