[
  {
    name: "MODEL FIESTA",
    ename: "model-fiesta",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "group",
    minSize: 4,
    maxSize: 4,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "WASTE-O-CRAFT",
    ename: "waste-o-craft",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "duo",
    minSize: 2,
    maxSize: 2,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "MEGA STRUCTURE",
    ename: "mega-structure",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "group",
    minSize: 4,
    maxSize: 6,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "START-UP-FAIR",
    ename: "start-up-fair",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "group",
    minSize: 1,
    maxSize: 5,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "CIRCUITRIX",
    ename: "circuitrix",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "single",
    minSize: 1,
    maxSize: 1,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "TOOL FINDER",
    ename: "tool-finder",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "single",
    minSize: 1,
    maxSize: 1,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "WEB WAR",
    ename: "web-war",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "single",
    minSize: 1,
    maxSize: 1,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "APP DEVELOPMENT",
    ename: "app-development",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "single",
    minSize: 1,
    maxSize: 1,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "BLIND CODING",
    ename: "blind-coding",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "single",
    minSize: 1,
    maxSize: 1,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "SOURCE CODE",
    ename: "source-code",
    gender: "both",
    registrationLastDate: "22th Jan",
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "CODE-O-SOCCOR",
    ename: "code-o-soccor",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "duo",
    minSize: 2,
    maxSize: 2,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "TECH QUIZ",
    ename: "tech-quiz",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "single",
    minSize: 1,
    maxSize: 1,
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
  {
    name: "ROBOTICS(SARS)",
    ename: "robotics-sars",
    gender: "both",
    registrationLastDate: "22th Jan",
    type: "group",
    poster: "",
    details: "",
    fees: "",
    category: "technical",
  },
];
